import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
const TIMELINE = [
    { y: "01", title: "Brand Foundation", body: "PASSION is founded in Lahore with a single ambition: to make unstitched fabric the most considered purchase a man makes." },
    { y: "02", title: "Collection Expansion", body: "Cotton, Wash & Wear and Latha series are introduced — each with proprietary finishing standards." },
    { y: "03", title: "International Tailoring Partnerships", body: "Direct supply relationships with master tailors across the GCC, UK and South-East Asia." },
    { y: "04", title: "Global Luxury Positioning", body: "Silicon Valley flagship opens; PASSION enters the conversation with the world's most respected fabric houses." },
];
export function FounderSection() {
    return (_jsx("section", { className: "relative overflow-hidden py-24 md:py-32", children: _jsxs("div", { className: "container-luxe", children: [_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 0.6 }, className: "mx-auto max-w-3xl text-center", children: [_jsx("p", { className: "eyebrow", children: "Letter from the founder" }), _jsxs("h2", { className: "mt-4 font-display text-[clamp(1.9rem,4vw,3rem)] font-semibold leading-[1.05] tracking-tight", children: ["\u201CRedefining men\u2019s elegance through", _jsx("br", {}), _jsx("span", { className: "text-gradient-brand", children: "precision fabric craftsmanship." }), "\u201D"] }), _jsx("p", { className: "mt-6 text-base leading-relaxed text-muted-foreground md:text-lg", children: "I founded PASSION on a quiet conviction: that the way a man dresses should begin long before the first stitch. The fabric is the first decision and the most lasting one. Everything we do \u2014 every weave, every finish, every advisor we train \u2014 exists to honour that decision." })] }), _jsx("div", { className: "mx-auto mt-16 max-w-3xl", children: TIMELINE.map((t, i) => (_jsxs(motion.div, { initial: { opacity: 0, x: -16 }, whileInView: { opacity: 1, x: 0 }, viewport: { once: true }, transition: { duration: 0.5, delay: i * 0.08 }, className: "group flex gap-5 border-t border-border/60 py-5 transition-colors hover:bg-secondary/40", children: [_jsx("span", { className: "font-display text-lg font-semibold text-violet", children: t.y }), _jsxs("div", { className: "flex-1", children: [_jsx("p", { className: "font-display text-base font-semibold", children: t.title }), _jsx("p", { className: "mt-1 text-sm text-muted-foreground", children: t.body })] })] }, t.title))) })] }) }));
}
