import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "@inertiajs/react";
import { motion } from "framer-motion";
import { ArrowRight } from "lucide-react";
export function ServicesSection({ collections }) {
    return (_jsx("section", { className: "relative py-24 md:py-32", children: _jsxs("div", { className: "container-luxe", children: [_jsx(SectionHeader, { eyebrow: "The Atelier", title: _jsxs(_Fragment, { children: ["Four signatures, ", _jsx("span", { className: "text-gradient-brand", children: "one philosophy." })] }), description: "Each collection is a study in restraint \u2014 refined materials, considered finishing, and the kind of detail you only notice when it's missing elsewhere." }), _jsx("div", { className: "mt-14 grid gap-6 sm:grid-cols-2 lg:grid-cols-4", children: collections.map((c, i) => {
                        const img = c.image_url ?? '';
                        return (_jsx(motion.div, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: "-40px" }, transition: { duration: 0.5, delay: i * 0.1 }, children: _jsxs(Link, { href: `/collections/${c.slug}`, className: "group relative flex flex-col overflow-hidden rounded-2xl border border-border/70 bg-card transition-all duration-500 hover:-translate-y-1 hover:shadow-luxe", children: [_jsxs("div", { className: "relative aspect-[4/5] overflow-hidden", children: [img ? (_jsx("img", { src: img, alt: c.name, loading: "lazy", className: "h-full w-full object-cover transition-transform duration-700 group-hover:scale-110" })) : (_jsx("div", { className: "flex h-full items-center justify-center bg-gradient-to-br from-violet/10 to-primary/10", children: _jsx("span", { className: "font-display text-4xl font-bold text-muted-foreground/30", children: c.name.charAt(0) }) })), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-black/50 via-transparent to-transparent opacity-0 transition-opacity duration-500 group-hover:opacity-100" }), _jsxs("div", { className: "absolute bottom-3 left-3 right-3 flex items-center justify-between rounded-xl border border-white/15 bg-black/40 px-3 py-2 text-white backdrop-blur opacity-0 transition-all duration-500 group-hover:opacity-100", children: [_jsx("span", { className: "text-[10px] uppercase tracking-widest text-white/70", children: "Explore" }), _jsx(ArrowRight, { className: "h-3.5 w-3.5" })] })] }), _jsxs("div", { className: "flex flex-1 flex-col p-4", children: [_jsx("h3", { className: "font-display text-base font-semibold leading-tight", children: c.name }), _jsx("p", { className: "mt-1 text-xs text-muted-foreground line-clamp-2", children: c.description })] })] }) }, c.slug));
                    }) }), _jsx(motion.div, { initial: { opacity: 0, y: 12 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, className: "mt-10 text-center", children: _jsxs(Link, { href: "/collections", className: "btn-luxe border border-border bg-background text-foreground hover:bg-secondary", children: ["View All Collections", _jsx(ArrowRight, { className: "h-4 w-4" })] }) })] }) }));
}
export function SectionHeader({ eyebrow, title, description, align = "left", }) {
    return (_jsxs("div", { className: align === "center" ? "mx-auto max-w-2xl text-center" : "max-w-2xl", children: [_jsx(motion.p, { initial: { opacity: 0, y: 8 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, className: "eyebrow", children: eyebrow }), _jsx(motion.h2, { initial: { opacity: 0, y: 16 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 0.6 }, className: "mt-4 font-display text-[clamp(1.9rem,4vw,3rem)] font-semibold leading-[1.05] tracking-tight", children: title }), description && (_jsx(motion.p, { initial: { opacity: 0, y: 12 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 0.6, delay: 0.1 }, className: "mt-5 text-base text-muted-foreground md:text-lg", children: description }))] }));
}
