import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Head, Link } from "@inertiajs/react";
import { motion } from "framer-motion";
import { ArrowRight } from "lucide-react";
import { Navbar } from "@/Layouts/navbar";
import { Footer } from "@/Layouts/footer";
import { ThemeProvider } from "@/Layouts/theme-provider";
import { StickyWhatsApp } from "@/Layouts/sticky-whatsapp";
export default function Collections({ collections }) {
    return (_jsx(ThemeProvider, { children: _jsxs("div", { className: "min-h-screen bg-background text-foreground", children: [_jsx(Navbar, {}), _jsxs("main", { className: "pt-20", children: [_jsxs(Head, { children: [_jsx("title", { children: "All Collections \u2014 PASSION" }), _jsx("meta", { name: "description", content: "Browse PASSION's complete collection of premium men's unstitched fabrics \u2014 Cotton, Wash & Wear, Latha, and bespoke selections." }), _jsx("meta", { property: "og:title", content: "Collections \u2014 PASSION" }), _jsx("meta", { property: "og:description", content: "Premium men's unstitched fabric collections." })] }), _jsx("section", { className: "bg-gradient-soft pt-32 pb-8 md:pt-40", children: _jsxs("div", { className: "container-luxe max-w-3xl", children: [_jsx("p", { className: "eyebrow", children: "The Collections" }), _jsxs("h1", { className: "mt-4 font-display text-[clamp(2.2rem,5vw,4rem)] font-semibold leading-[1.05] tracking-tight", children: ["Every length, ", _jsx("span", { className: "text-gradient-brand", children: "considered." })] }), _jsx("p", { className: "mt-6 max-w-xl text-base text-muted-foreground md:text-lg", children: "Four signature collections, each refined to a single purpose. Tap any tile to discover its story." })] }) }), _jsx("section", { className: "py-12 md:py-20", children: _jsx("div", { className: "container-luxe", children: _jsx("div", { className: "grid gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4", children: collections.map((c, i) => {
                                        const img = c.image_url ?? '';
                                        return (_jsx(motion.div, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: "-40px" }, transition: { duration: 0.5, delay: i * 0.06 }, children: _jsxs(Link, { href: `/collections/${c.slug}`, className: "group relative flex flex-col overflow-hidden rounded-2xl border border-border/70 bg-card transition-all duration-500 hover:-translate-y-1 hover:shadow-luxe", children: [_jsxs("div", { className: "relative aspect-[4/5] overflow-hidden", children: [img ? (_jsx("img", { src: img, alt: c.name, loading: "lazy", className: "h-full w-full object-cover transition-transform duration-700 group-hover:scale-110" })) : (_jsx("div", { className: "flex h-full items-center justify-center bg-gradient-to-br from-violet/10 to-primary/10", children: _jsx("span", { className: "font-display text-5xl font-bold text-muted-foreground/30", children: c.name.charAt(0) }) })), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-black/50 via-transparent to-transparent opacity-0 transition-opacity duration-500 group-hover:opacity-100" }), _jsxs("div", { className: "absolute bottom-3 left-3 right-3 flex items-center justify-between rounded-xl border border-white/15 bg-black/40 px-3 py-2 text-white backdrop-blur opacity-0 transition-all duration-500 group-hover:opacity-100", children: [_jsx("span", { className: "text-[10px] uppercase tracking-widest text-white/70", children: "Explore" }), _jsx(ArrowRight, { className: "h-3.5 w-3.5" })] })] }), _jsxs("div", { className: "flex flex-1 flex-col p-4", children: [_jsx("h3", { className: "font-display text-base font-semibold leading-tight", children: c.name }), _jsx("p", { className: "mt-1 text-xs text-muted-foreground line-clamp-2", children: c.description })] })] }) }, c.slug));
                                    }) }) }) })] }), _jsx(Footer, {}), _jsx(StickyWhatsApp, {})] }) }));
}
